# Generated by Django 5.1.1 on 2024-10-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TSC", "0006_userprofile_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="mobile",
            new_name="phone",
        ),
        migrations.AddField(
            model_name="orders",
            name="role",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
