# Generated by Django 5.1.1 on 2024-10-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TSC", "0007_rename_mobile_orders_phone_orders_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Available for booking", "Available for booking"),
                    ("Not available currently", "Not available currently"),
                    ("Not for Booking", "Not for booking"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
