# Generated by Django 5.1.1 on 2024-10-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("TSC", "0008_room_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out",
            field=models.DateTimeField(),
        ),
    ]
