# Generated by Django 5.1.1 on 2024-10-21 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("TSC", "0010_userprofile_ref_contact_userprofile_ref_dept_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="ref_national_id",
            new_name="national_id",
        ),
    ]
