# Generated by Django 5.1.2 on 2024-10-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSC', '0012_alter_booking_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='item',
        ),
        migrations.AddField(
            model_name='orders',
            name='items_summary',
            field=models.TextField(null=True),
        ),
    ]
