# Generated by Django 5.1.2 on 2024-12-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSC', '0017_alter_booking_tot_price_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tot_price',
            field=models.IntegerField(default=0),
        ),
    ]
