# Generated by Django 5.1.5 on 2025-03-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSC', '0019_alter_menuitem_price_alter_orders_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='meal_times',
            field=models.ManyToManyField(related_name='menu_items', to='TSC.mealtime'),
        ),
    ]
