# Generated by Django 5.1.5 on 2025-04-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSC', '0021_alter_booking_payment_method_alter_mealtime_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
